In [1]:
import numpy as np

1. Create a vector with values ranging from 10 to 49.

In [2]:
arr = np.arange(10,50)
print(arr)
print()

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]



2. Create a 3x3 matrix with values ranging from 0 to 8.

In [3]:
arr = np.arange(9).reshape(3,3)
print(arr)
print()

[[0 1 2]
 [3 4 5]
 [6 7 8]]



3. Create a 3x3 identity matrix.

In [4]:
arr = np.eye(3)
print(arr)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



4. Create a 3x3x3 array with random values.

In [5]:
arr = np.random.rand(3,3,3)
print(arr)
print()

[[[0.47190537 0.36432929 0.47011138]
  [0.70068995 0.21213332 0.20082763]
  [0.12331644 0.04272614 0.42213202]]

 [[0.51909759 0.53843152 0.67109831]
  [0.15970958 0.86926604 0.70010673]
  [0.81758443 0.78230911 0.82138855]]

 [[0.80087221 0.72886077 0.76101192]
  [0.40322402 0.46464882 0.9743592 ]
  [0.03332218 0.73282723 0.58154821]]]



5. Create a 10x10 array with random values and find the minimum and maximum values.

In [6]:
arr = np.random.rand(10,10)
print(arr.min())
print()

0.0007567516768315352



6. Create a random vector of size 30 and find the mean value.

In [7]:
arr = np.random.rand(30)
print(arr.mean())
print()

0.47424509861326186



7. Normalize a 5x5 random matrix.

In [8]:
arr = np.random.rand(5,5)
normalized = (arr - arr.mean(axis=0)) / arr.std(axis=0)
print(normalized)
print()

[[-1.32197207 -1.27985941 -0.0138571   0.27632349  0.95949675]
 [-0.69369392 -0.89040955  0.37598266 -1.3116338  -1.12866027]
 [ 1.52982227  0.84066922  1.21677969  1.02025326  0.43083643]
 [ 0.63839648  1.36425975  0.24288001  1.04729581  1.00618501]
 [-0.15255276 -0.03466    -1.82178526 -1.03223877 -1.26785791]]



8. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [9]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)

result = np.dot(matrix1,matrix2)
print(result)
print()

[[1.08194649 0.23897132]
 [1.01186011 0.36088709]
 [1.17765776 0.21000862]
 [0.96294759 0.38538116]
 [1.16718914 0.38017783]]



9. Create two 3x3 matrices and compute their dot product.

In [10]:
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
result = np.dot(matrix1, matrix2)

print(result)
print()

[[0.53940264 0.35488628 0.32157426]
 [1.13213191 0.79991499 0.76445863]
 [1.33720917 0.98452817 0.88844202]]



10. Given a 4x4 matrix, find its transpose.

In [11]:
matrix = np.random.rand(4,4)
transpose = matrix.T
print(transpose)
print()

[[0.6649364  0.76294963 0.19655707 0.82514687]
 [0.38048561 0.18244939 0.84573638 0.15387247]
 [0.24543296 0.56632442 0.57256095 0.97309894]
 [0.10585255 0.06061839 0.29028797 0.59026694]]



11. Create a 3x3 matrix and calculate its determinant.

In [12]:
matrix = np.random.rand(3,3)
determinant = np.linalg.det(matrix)

print(determinant)
print()

-0.09367236387515473



12. Create two matrices ( A ) (3x4) and ( B ) (4x3), and compute the matrix product ( A \cdot B ).

In [13]:
matrix_A = np.random.rand(3, 4)
matrix_B = np.random.rand(4, 3)

result = np.dot(matrix_A, matrix_B)
print(result)
print()

[[1.53034367 1.10740657 0.67599876]
 [1.8136055  1.14112711 0.59561913]
 [1.39175351 0.56256174 0.23966092]]



13. Create a 3x3 random matrix and a 3-element column vector. Compute the matrix-vector product.

In [14]:
matrix = np.random.rand(3, 3)
vector = np.random.rand(3, 1)
result = np.dot(matrix, vector)

print(result)
print()

[[1.4240191 ]
 [0.95226314]
 [1.1689861 ]]



14. Solve the linear system ( Ax = b ) where ( A ) is a 3x3 matrix, and ( b ) is a 3x1 column vector.

In [15]:
matrix_A = np.random.rand(3, 3)
vector_b = np.random.rand(3, 1)

solution = np.linalg.solve(matrix_A, vector_b)

print(solution)
print()

[[-0.61063609]
 [ 0.19191854]
 [ 1.4153896 ]]



15. Given a 5x5 matrix, find the row-wise and column-wise sums.

In [16]:
matrix = np.random.rand(5, 5)

row_sums = matrix.sum(axis=1)
column_sums = matrix.sum(axis=0)
print(row_sums)
print(column_sums)
print()

[1.88136996 2.54345233 3.84718633 2.61314618 1.64005664]
[1.93029873 1.85850882 3.5005585  2.76467297 2.47117242]

